server:
  port: ${PORT:8761}

eureka:
  server:
    eviction-interval-timer-in-ms: 5000
  client:
    registry-fetch-interval-seconds: 30
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:${server.port}/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
    instance-id: ${EUREKA_INSTANCE_HOSTNAME:localhost}:${server.port}@${random.long(1000000,9999999)}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: "*"