apiVersion: v1
kind: Service
metadata:
  name: organization-sample
  namespace: kubesphere-springcloud-sample
  labels:
    app: organization-sample
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: organization-sample
  selector:
    app: organization-sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: organization-sample
  name: organization-sample
  namespace: kubesphere-springcloud-sample
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: organization-sample
  template:
    metadata:
      labels:
        app: organization-sample
        version: master-$BUILD_NUMBER
    spec:
      initContainers:
        - name: wait-config
          image: 'busybox:1.28.4'
          command:
            - sh
            - '-c'
            - >-
              until nc -z config-sample 8080; do echo "waiting for
                            config"; sleep 2; done;
        - name: wait-eureka
          image: 'busybox:1.28.4'
          command:
            - sh
            - '-c'
            - >-
              until nc -z eureka-sample 8761; do echo "waiting for
                            eureka"; sleep 2; done;
      containers:
        - image: 192.168.23.157/demo/organization-sample:latest
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
            initialDelaySeconds: 180
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
            initialDelaySeconds: 180
          env:
            - name: PORT
              value: "8080"
            - name: CONFIG_SERVER
              value: "http://config-sample:8080"
            - name: EUREKA_SERVER
              value: "http://eureka-sample-0.eureka-sample:8761/eureka/,http://eureka-sample-1.eureka-sample:8761/eureka/,http://eureka-sample-2.eureka-sample:8761/eureka/"
          imagePullPolicy: Always
          name: organization-sample
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
#      imagePullSecrets: 
#      - name: mydockerhub
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30